version: "3.8"
services:

  postgresql:
    container_name: blog-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./db/dev:/var/lib/postgresql/data
    networks:
      - blog
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phx_blog

  webapp:
    container_name: webapp
    build:
      context: ..
      dockerfile: Dockerfile
    image: webapp:latest
    ports:
      - "4000:4000"
    networks:
      - blog
    depends_on:
      - postgresql
    environment:
      - DB_ROOT_PASSWORD=postgres
      - DB_ROOT_HOSTNAME=postgres
      - DB_POOL_SIZE=3
      # - AWS_IMAGE_ACCESS_KEY_ID=
      # - AWS_IMAGE_SECRET_KEY=WmMl4+I7CA9a/WxLl17PJ6/IOw8Yognhg35d3g5C
      # - AWS_S3_IMAGE_HOST=macrostax-team-images.s3.us-east-2.amazonaws.com
      # - AWS_S3_IMAGE_SCHEME=https://
      # - AWS_S3_IMAGE_REGION=us-east-2
      
networks:
  blog:
