version: "3.8"
services:

  postgresql:
    container_name: blog-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./db/dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phx_blog_dev

  webapp:
    container_name: webapp
    build:
      context: ..
      dockerfile: Dockerfile
    image: webapp:latest
    ports:
      - "4000:4000"
    depends_on:
      - postgresql
    environment:
      - DB_POOL_SIZE=3
#################################### added 
      - DATABASE_URL=ecto://postgres:postgres@localhost/phx_blog_dev
      - SECRET_KEY_BASE=37gj1uv6QFrvyB14f41SrJCqUgnkQ8IGCRDpehJb8jAuELRB1XGPXGdGTeSqV7CV
